version: "3.4"

services:
  swagger:
    image: swaggerapi/swagger-ui
    network_mode: "host"
    ports:
      - "80:8080"
    environment:
      - SWAGGER_JSON=/api/swagger_doc.json
      - API_URL= http://52.57.253.240:3000/api/swagger_doc.json
