version: "3.4"

services:
  swagger:
    image: swaggerapi/swagger-ui
    network_mode: "host"
    ports:
      - "80:8080"
    environment:
      - API_URL=${RAILS_HOST}${SWAGGER_JSON}
    env_file: .env
