version: "3.4"

services:
  api:
    container_name: "event-api"
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - ./storage:/home/backend/storage
